### ISSUE TITLE
Minor potential typo in `FastaInterval` class

### ISSUE THREAD

**Issue by sofroniewn** [lucidrains/enformer-pytorch#14]
Hello, first off thanks so much for this incredible repository, it's greatly accelerating a project I am working on!

I've been using the `GenomeIntervalDataset` class and notice a minor potential typo in the `FastaInterval` class when I was trying to fetch a sequence with a negative start position and got an empty tensor back. It looks like there is logic for clipping the start position at 0 and padding the sequence here https://github.com/lucidrains/enformer-pytorch/blob/ab29196d535802c8a04929534c5860fb55d06056/enformer_pytorch/data.py#L137-L143 but that it wasn't being used in my case as it was inside the above if clause that I wasn't triggering https://github.com/lucidrains/enformer-pytorch/blob/ab29196d535802c8a04929534c5860fb55d06056/enformer_pytorch/data.py#LL128C9-L128C82. If I unindent that logic then everything worked fine for me.

If it was unintentional to have the clipping inside that if clause I'd be happy to submit a trivial PR to fix the indentation.

Thanks again for all your work

**Comment by lucidrains** [comment]
@sofroniewn thank you for the kind words, and for finding this edge case! i've patched it in [0.5.6](https://github.com/lucidrains/enformer-pytorch/commit/8fe99cf5365f2296236522c79216b4dec0646128)

**Comment by sofroniewn** [comment]
You're welcome. Thanks for the quick fix and release 🚀
