### ISSUE TITLE
Minor typo in data.py

### ISSUE THREAD

**Issue by icdh99** [lucidrains/enformer-pytorch#19]
Hi! 

I have just started working with this repository, thank you for making this! I am trying to use the GenomicIntervalDataset to supply a sequence in fasta format, and I think I found a spelling mistake that creates an error. In the file enformer_pytorch/data.py and then in line 189, the line reads `df = pl.read_csv(str(bed_path), sep = '\t', has_headers = False)`. However, according to the polars documentation, it should be `has_header`. 

This is the error I got that lead me to this: TypeError: `read_csv() got an unexpected keyword argument 'has_headers'`.

Please let me know if you can change this!

**Comment by lucidrains** [comment]
@icdh99 hey! should be fixed in 0.6.1, thank you!

**Comment by lucidrains** [comment]
@icdh99 just curious, whose lab are you working for?

**Comment by icdh99** [comment]
Hi Phil,

Thank you for fixing the issue so quickly! I just started my Master’s internship at the lab of dr. Mahfouz, at Leiden University Medical Center. I will most likely be working with your repo a lot, so I might bother you with more questions in due time :)

Best,
Inez
