### ISSUE TITLE
Initializing AttentionPool weights with 2 * Identity matrix, again!

### ISSUE THREAD

**Issue by dohlee** [lucidrains/enformer-pytorch#22]
Thank you for the quick fix for my recent issue (https://github.com/lucidrains/enformer-pytorch/issues/21)! `nn.init.dirac_` is a great solution. 

However there's one more thing: we have to initialize the weight with a Identity matrix **multiplied by 2!**

![image](https://user-images.githubusercontent.com/30403812/218289634-a4bfafd7-1fc0-42de-a287-380446da1a38.png)

Of note, the official deepmind Sonnet implementation of enformer uses `snt.initializers.Identity` with `gain=2`.
(Please refer code lines [here](https://github.com/deepmind/deepmind-research/blob/cb555c241b20c661a3e46e5d1eb722a0a8b0e8f4/enformer/enformer.py#L236) and [here](https://github.com/deepmind/deepmind-research/blob/cb555c241b20c661a3e46e5d1eb722a0a8b0e8f4/enformer/enformer.py#L274) in deepmind implementation)

Thanks,
Dohoon

**Comment by lucidrains** [comment]
@dohlee oh yup, i later updated it [here](https://github.com/lucidrains/enformer-pytorch/commit/4e70710443a6a2630cbc64e5e95370f4cf03fc93#diff-731a654b4db822b88ef1d1d3b5f14b1ea57404644af71870c99273655b4dd5a6R145)

probably should have just gone with your solution 😅

**Comment by dohlee** [comment]
Oh sorry I didn't notice that commit. No problem at all :)

I'll keep on reviewing the code. Really informative!

**Comment by lucidrains** [comment]
@dohlee ok, do send me an email if you get any great results with fine tuning!
