### ISSUE TITLE
GenomeIntervalDataset problems

### ISSUE THREAD

**Issue by tcztzy** [lucidrains/enformer-pytorch#26]
https://github.com/lucidrains/enformer-pytorch/blob/e3aeba1a29d3ff8776e65342044159b7ee4be61f/enformer_pytorch/data.py#L191

According to the [doc](https://pola-rs.github.io/polars/py-polars/html/reference/api/polars.read_csv.html#polars.read_csv), there is no parameter named `sep`, but only `seperator`.

`.bed` is binary file, directly `read_csv` will cause the encoding error. Maybe the `.bed` is [UCSC Genome Browser's BED format](https://genome.ucsc.edu/FAQ/FAQformat.html#format1) instead of [PLINK1 binary](https://www.cog-genomics.org/plink2/formats#bed). If so, it needs to be stated in the documentation

**Comment by lucidrains** [comment]
@tcztzy oh interesting, maybe i was using an older version of polars

anyways, both points addressed, thanks! https://github.com/lucidrains/enformer-pytorch/commit/3cbcd94e918145eeeef11725944e73210e95380e
