### ISSUE TITLE
Using transformers[torch] to limit dependencies

### ISSUE THREAD

**Issue by gokceneraslan** [lucidrains/enformer-pytorch#27]
I think right now the transformers dependency brings in not only torch but also Jax, tensorflow  etc which are not relevant for enformer-pytorch. 

I just found out that using transformers[torch] brings only the torch dependency (eg https://github.com/huggingface/transformers/issues/23666). Would it make sense to simply use it in setup.py instead?

**Comment by lucidrains** [comment]
ah yea sure, let me make that change! i'm guessing your group must be using this repository a lot to request this?
