### ISSUE TITLE
Gradient checkpoint

### ISSUE THREAD

**Issue by fransilvionGenomica** [lucidrains/enformer-pytorch#33]
Hi, I noticed you have a version of the trunk with gradient checkpoints for transformer layers. Is it safe to use it like this since there are many non-zero dropout layers for both attention and feed forward layers? Since the checkpointing API runs the forward pass twice on the checkpointed segment of the model and dropout drops values arbitrarily, it means that output values won't match?

**Comment by lucidrains** [comment]
yea it should be safe, as the pytorch team does some magic with the RNG

but you should check on that. highly doubt they didn't handle this obvious case

**Comment by lucidrains** [comment]
https://pytorch.org/docs/stable/checkpoint.html yeah they preserve the RNG states unless you turn it off
