### ISSUE TITLE
Why do we need Residual here while we have residual connection inside conv block

### ISSUE THREAD

**Issue by inspirit** [lucidrains/enformer-pytorch#6]
we wrap conv block inside Residual:
https://github.com/lucidrains/enformer-pytorch/blob/1cbbe860bbd3ce8c26cee3de149d4fcdba508d95/enformer_pytorch/modeling_enformer.py#L318

while we have residual connection already inside conv block here:
https://github.com/lucidrains/enformer-pytorch/blob/1cbbe860bbd3ce8c26cee3de149d4fcdba508d95/enformer_pytorch/modeling_enformer.py#L226

**Comment by jstjohn** [comment]
Good point. The ConvNextBlock is an experimental feature. The regular conv block which does not have the built in residual needs it. I don’t think the convnextblock outperformed the default…

**Comment by lucidrains** [comment]
@inspirit hey Eugene! thanks for catching this! and indeed, as @jstjohn John noted, convnext blocks didn't really outperform the resnet. I'm just going to remove it, as we already have the working pretrained model from deepmind.
