### ISSUE TITLE
example data files

### ISSUE THREAD

**Issue by yingyuan830** [lucidrains/enformer-pytorch#7]
Hi, in the README, you mentioned to use sequences.bed and hg38.ml.fa files to build the GenomeIntervalDataset, but I can't find these example data files, could you provide the links of these files ? Thanks!

**Comment by lucidrains** [comment]
@yingyuan830 Hi Ying

You can follow these instructions to get the hg38 reference genome fasta file, as well as the bed file that was used for enformer training, but you'll probably be supplying your own bed file for finetuning https://github.com/lucidrains/enformer-tensorflow-sonnet-training-script#downloading-sequence-data-for-extending-context-length-to-196608

**Comment by yingyuan830** [comment]
thanks!

**Comment by biginfor** [comment]
Due to some security reasons, I am unable Google Cloud in my country. Can anyone share training files with me? I will be very grateful!
